#! /usr/bin/python


#n -> n/2 (n is even)
#n -> 3n + 1 (n is odd)

r = 13
ans = {}
cmax = 0
i = 1

for i in range (2,1000000):
  c = 0
  r = i
  #print "\nstart with %i" % r
  #print r
  while (r > 1):
    if r not in ans:
      if (r%2==0):
        r = r/2
      else:
        r = 3*r + 1
      c+=1
      #print r
      # print "%i(%i)" % (r,c)
    else:
      c = c + ans[r]
      break

  if i not in ans:
    ans[i] = c
  
  if cmax < c:
    cmax = c
    print "%i .. 1 -> c = %i\n---------\n" % (i,c+1)
  

#print ans
