#! /usr/bin/python


def fac (n):
  if (n<=1):
    return 1
  else:
    return fac(n-1)*n


def T(i,j):
  if i==1 or j == 1:
    return 1
  else:
    return T(i-1,j) + T(i,j-1) + T(i-1,j-1)
    

for N in range(1,22):    
  print fac(2*N - 2)/(fac(N - 1)**2)
  
