#! /usr/bin/python
import sys
a = {}

a[1] = "one"
a[2] = "two"
a[3] = "three"
a[4] = "four"
a[5] = "five"
a[6] = "six"
a[7] = "seven"
a[8] = "eight"
a[9] = "nine"
a[10] = "ten"
a[11] = "eleven"
a[12] = "twelve"
a[13] = "thirteen"
a[14] = "fourteen"
a[15] = "fifteen"
a[16] = "sixteen"
a[17] = "seventeen"
a[18] = "eighteen"
a[19] = "nineteen"

a[20] = "twenty"
a[30] = "thirty"
a[40] = "forty"
a[50] = "fifty"
a[60] = "sixty"
a[70] = "seventy"
a[80] = "eighty"
a[90] = "ninety"
a[1000] = "onethousand"


for i in range(20,100,10):
  for j in range (1,10): 
    a[i+j] = a[i] + "" + a[j]

for i in range(1,10):
  a[i*100] = a[i] + "hundred"

for i in range(100,1000,100):
  for j in range (1,100):
    a[i+j] = a[i] + "and" + a[j]    
    
    
s = 0    
for n in a.values():
  s += len (n)
  sys.stdout.write ("%s, " % n)
print s
