#! /usr/bin/python

#The fraction 49/98 is a curious fraction, as an inexperienced mathematician in attempting to #simplify it may incorrectly believe that 49/98 = 4/8, which is correct, is obtained by cancelling the 9s.

#We shall consider fractions like, 30/50 = 3/5, to be trivial examples.

#There are exactly four non-trivial examples of this type of fraction, less than one in value, and containing two digits in the numerator and denominator.

#If the product of these four fractions is given in its lowest common terms, find the value of the denominator.

print float(49)/98

# 49/98

print 40 * 24 * 48 * 98

numerator = 1
denominator = 1

for i in range (10,99):
  for j in range (i + 1,99):
    si1 = str(i)[0]
    si2 = str(i)[1]

    sj1 = str(j)[0]
    sj2 = str(j)[1]

    same = False
    if sj1 == "0" or sj2 == "0": continue

    if si1 == sj1:
      if float(si2)/float(sj2) == float(i)/float(j):
        same = True;

    if si1 == sj2:
      if float(si2)/float(sj1) == float(i)/float(j):
        same = True;

    if si2 == sj1:
      if float(si1)/float(sj2) == float(i)/float(j):
        same = True;

    if si2 == sj2:
      if float(si1)/float(sj1) == float(i)/float(j):
        same = True;

    if same:
      print "%i / %i" % (i,j)
      numerator *= i
      denominator *= j


print numerator
print denominator

#print 95* 65 * 64 * 98
#print 19* 16 * 26 * 49

