#! /usr/bin/python


# 145 is a curious number, as 1! + 4! + 5! = 1 + 24 + 120 = 145.

# Find the sum of all numbers which are equal to the sum of the factorial of their digits.

# Note: as 1! = 1 and 2! = 2 are not sums they are not included.

# WTF?? Only 145 seems to be CURIOUS?? No others.

facs = {}

MAXFAC = 9

def create_facs (n):
  facs[0] = 1
  facs[1] = 1
  for i in range(2, n + 1):
    facs[i] = facs[i - 1] * i
  
create_facs(MAXFAC)

print "Done initializing."
print facs[0]
print facs[1]
print facs[2]
print facs[3]

total_sum = 0

for i in range (1,9999999):
  s = 0
  for d in str(i):
    s += facs[int(d)]
  if (s == i):
    print i
    total_sum += i
#  else:
#    print "%i, sum: %i" % (i,s)

print total_sum
