#! /usr/bin/python

# 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
# What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

def fac (n):
  if (n==1):
    return n
  else:
    return fac(n-1)*n


#print fac(20) /2/3/4/5/6/7/8/9/10


for i in range (0,900000000,20):
  x = False
  for d in range(3,20,1): #[7,11,12,13,14,15,16,17,18,19,20]:
    if (i%d!=0):
      x=True
      break

  if (not x):
    print i


