#! /usr/bin/python
# -*- coding: utf-8 -*-

def same_digits(x,y):
  if x == y: 
    return True
  a = str(x)
  b = str(y)
  if len(a) != len(b):
    return False
  if sorted(a) == sorted(b):
    return True

  return False

for i in range(1,1000000):
  i2 = 2*i  
  i3 = 3*i
  i4 = 4*i
  i5 = 5*i
  i6 = 6*i
#  print "i,i2: %d,%d" % (i2,i3)
  if same_digits(i2,i3):
#   print "i2,i3: %d,%d" % (i2,i3)
    if same_digits(i2,i4):
#      print "i2,i4: %d,%d" % (i2,i4)
       if same_digits(i2,i5):
#        print "i2,i5: %d,%d" % (i2,i5)
         if same_digits(i2,i6):
           print "i,i2,i6: %d,%d,%d" % (i,i2,i6)




#print same_digits(42,24)
#print same_digits(99,99)
#print same_digits(151,511)
#print same_digits(151,111)

