#! /usr/bin/python
# -*- coding: utf-8 -*-

avg = 0.0

for n in range(2,20):
  print n
  count = 0
  for i in range(1,n):
    if n%i != 0:
      print "Found %i" % i
      count+=1
  if count != 0 and float(n)/count > avg:
    avg = float(n)/count
    print "Found new avg for %i: %f" % (n,avg)
