#! /usr/bin/python

# How many Sundays fell on the first of the month during the twentieth century (Tuesday 1 Jan 1901 to 31 Dec 2000)?
# Sunday = 6 Jan


def days_m(n,y):
  months = {0:31,1:28,2:31,3:30,4:31,5:30,6:31,7:31,8:30,9:31,10:30,11:31}
  if (y%4==0):
    months[1] = 29
  
  return months[n]

def sunday(d):
  return d%7==6

d = 0
sundays = 0
for y in range(1901,2000):
  for m in range(0,12):
     d += days_m(m,y)
     if (sunday(d)):
       sundays += 1
       
print sundays
    
