#! /usr/bin/python


import bisect

class sortlist:
    def __init__(self, list):
        self.list = list
        self.sort()
    def sort(self):
        l = []
        for i in range(len(self.list)):
            bisect.insort(l, self.list[i])
        self.list = l
        self.len = len(self.list)
    def insert(self, value):
        if not value in self.list:
          bisect.insort(self.list, value)
          self.len += 1
    def show(self):
        print self.list
    def search(self,value):
        left = bisect.bisect_left(self.list, value)
        if abs(self.list[min([left,self.len-1])] - value) >= abs(self.list[left-1] - value):
            return self.list[left-1]
        else:
            return self.list[left]

l = sortlist([])


#x = {}
for i in range (2,101):
  for j in range (2,101):
      l.insert(j**i)
    
l.show()    
print l.len
