#! /usr/bin/python
coins = [1,2,5,10,20,50,100,200]
amount = 200

C = [[0 for c in range(amount + 1)] for r in range (len(coins))]

for i in range(len(C)):
  C[i][0] = 1

for r in C: print r


for i in range(len(coins)):
  for j in range(1,amount + 1):
    C[i][j] = C[i-1][j] + C[i][j-coins[i]]

print "--"
for r in C: print r

print C[len(coins)-1][amount]
