#! /usr/bin/python

import string

primes = []



def is_prime(n):
    '''check if integer n is a prime'''
    # 0 and 1 are not primes
    if n < 2:
        return False
    # 2 is the only even prime number
    if n == 2: 
        return True    
    # all other even numbers are not primes
    if not n & 1: 
        return False
    # range starts with 3 and only needs to go up the squareroot of n
    # for all odd numbers
    for x in range(3, int(n**0.5)+1, 2):
        if n % x == 0:
            return False
    return True

# 2,3,5,7, 11, 13, 17, 31, 37, 71, 73, 79, and 97



  
primes.append("2")  
for i in range (3,100,2):
  if is_prime(i):
    primes.append(''.join(sorted(str(i))))

#print primes
primes = list(sorted(primes))
#print primes


#[i for i in my_list if i.attribute == value]
print primes

from itertools import groupby
nrs = [ (key) for key, group in groupby(primes) if (len(list(group)) == len(key))]
print nrs
amount = 0
for nr in nrs:
  amount += len(nr)
  
print amount

#primes = list(set(primes))
#print len((primes))



