#! /usr/bin/python

def is_palindrome(n):
  s_10 = str(n)
  s_2 = str(bin(n)[2:])
  if (s_10==s_10[::-1] and s_2==s_2[::-1]):
#    print "%i is a palindrome" % n
    return True
    
    
s = 0
for i in range(1,1000000):
  if (is_palindrome(i)):
    print i
    s+=i
    
print s
