#! /usr/bin/python

def is_truncatable(n):
  s = str(n)
  prime = True
  if (len(s) == 1): return False
  for i in range(1,len(s)):
    if not is_prime(int(s[:-i])):
      prime = False
    if not is_prime(int(s[i:])): 
      prime = False

  return prime

def is_prime (n):
  for i in range(2,int(n**0.5)+1):
    if (n%i==0):
      return False
  return n>=2

s = 0
for i in range (3,1000000,2):
  if (is_prime(i)):
    if is_truncatable(i):
      s+=i
      print i
      
print s

