#! /usr/bin/python

# A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 x 99.
# Find the largest palindrome made from the product of two 3-digit numbers.

def is_palindrome(n):
  s = str(n)
  if (s==s[::-1]):
    print "%i is a palindrome" % n
    return True
  




n1 = 999
n2 = 999
m = 0

while n1 > 100:
  while n2 > n1:
    #print "%i,%i" % (n1,n2)
    if (is_palindrome(n1*n2)):
      m = max(m,n1*n2)
      print "%i * %i" % (n1,n2)
    n2-=1
  n2 = 999
  n1-=1

print m
