#! /usr/bin/python

# By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
# What is the 10 001st prime number?

def is_prime (n):
  i = 2
  while (i < n):
    if (n%i==0):
	  return False
    i+=1
  return n>=2

count = 1

for i in range (3,100000000,2):
  if (is_prime(i)):
    count+=1
  if count == 5001:	
    print "halfway!"
  if count == 10001:
    print i

